image: dkudlek/gcc13.2.0-gtest14.4.0



build:static:release:
  stage: build
  before_script:
    - cwd=$(pwd)
    - cd /opt
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.vnet.kudlek.online/dkudlek/cmake_playground.git
    - cd cmake_playground 
    - mkdir build 
    - cd build 
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/cmake_playground
    - cmake --build . --config Release --target install
    - cd $cwd
    - export PATH="/usr/local/cmake_playground/cmake:$PATH"
    - export PATH="/usr/local/lib/cmake/GTest:$PATH"
  script:
    - mkdir build_static_release
    - cd build_static_release
    - cmake .. -DCMAKE_INSTALL_PREFIX=../install
    - cmake --build . --config Release --target install
  artifacts:
    paths:
      - build_static_release