image: gcc
stages:
  - configure
  - build
#  - test
#  - deploy


ci_example_configure:WSL:
 stage: configure
 before_script:
  - apt-get update --yes
  - apt-get install --yes cmake
  - eval $(ssh-agent)
#  - echo ${SSH_PRIVATE_KEY}
#  - cat ${SSH_PRIVATE_KEY}
  - echo "$SSH_PRIVATE_KEY"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - cp $SSH_PRIVATE_KEY ~/.ssh/id_rsa
  - cp $SSH_PUBLIC_KEY ~/.ssh/id_rsa.pub
  - chmod 600 ~/.ssh/id_rsa
  - chmod 644 ~/.ssh/id_rsa.pub
  - ssh-add ~/.ssh/id_rsa
  - ssh-add -l
  - cat ~/.ssh/id_rsa
  - ssh-keyscan -p 9002 -t rsa -H gitlab.vnet.kudlek.online >> ~/.ssh/known_hosts
  - cat ~/.ssh/known_hosts
  - ssh -p 9002 -vT git@gitlab.vnet.kudlek.online
  - git clone --progress --verbose ssh://git@gitlab.vnet.kudlek.online:9002/dkudlek/cmake_playground.git
  - cd cmake_playground
  - cd build
  - cmake ..
  - cmake --build .

 script:
  - echo configure stage
  - mkdir build
  - cd build
  - cmake ..
 artifacts:
  paths:
   - build

ci_example_build:WSL:
 stage: build
 before_script:
  - apt-get update --yes
  - apt-get install --yes cmake
 script:
  - echo build stage
  - cd build
  - cmake --build .
 artifacts:
  paths:
   - build
 dependencies:
  - ci_example_configure:WSL

#ci_example_test:WSL:
# stage: test
# tags:
#  - wsl
# script:
#  - cd build
#  - wsl ctest . -C Debug
# dependencies:
#  - ci_example_build:WSL


## Common deploy
#ci_example_deploy:
# stage: deploy
# tags:
#  - windows
#  - wsl
# script:
#  - echo deploy
# dependencies: []
# artifacts:
#  paths:
#   - src/lib.hpp
