image: gcc
stages:
  - configure
  - build
#  - test
#  - deploy


ci_example_configure:WSL:
 stage: configure
 before_script:
  - apt-get update --yes
  - apt-get install --yes cmake
 script:
  - git clone http://gitlab.vnet.kudlek.online/dkudlek/cmake_playground.git
  - cd cmake_playground
  - cd build
  - cmake ..
  - cmake --build .
  - cd ../../ 
  - echo configure stage
  - mkdir build
  - cd build
  - cmake ..
 artifacts:
  paths:
   - build

ci_example_build:WSL:
 stage: build
 before_script:
  - apt-get update --yes
  - apt-get install --yes cmake
 script:
  - echo build stage
  - cd build
  - cmake --build .
 artifacts:
  paths:
   - build
 dependencies:
  - ci_example_configure:WSL

#ci_example_test:WSL:
# stage: test
# tags:
#  - wsl
# script:
#  - cd build
#  - wsl ctest . -C Debug
# dependencies:
#  - ci_example_build:WSL


## Common deploy
#ci_example_deploy:
# stage: deploy
# tags:
#  - windows
#  - wsl
# script:
#  - echo deploy
# dependencies: []
# artifacts:
#  paths:
#   - src/lib.hpp
